language: node_js

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
    - export CXX="g++-4.8"

node_js:
    - '4.2'

before_script:
    - npm install juttle@^0.7.0

script:
    - npm run test-coverage
    - npm run check-coverage
